apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: coreapp-config-v1-configevent
spec:
  type: PROTOCOL_BUFFER
  definition: |
    syntax = "proto2";
    message ConfigEvent {
      oneof event_data {
        Inline_coreapp_config_v1_ConfigUpdatedEventData eventUpserted = 1;
      }
      message Inline_coreapp_config_v1_ConfigUpdatedEventData {
        optional string id = 1;
      }
    }
    